# action.yml
name: 'Upload source maps to Bugsnag'
description: 'Upload source maps to Bugsnag'
inputs:
  upload:
    description: 'upload browser or server'
    required: true
    default: 'upload-browser'
  api-key:
    description: 'Api key'
    required: true
  app-version:
    description: 'App version'
    required: true
  base-url:
    description: 'Base url'
    required: true
  directory:
    description: 'Directory'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.upload }}
    - ${{ inputs.api-key }}
    - ${{ inputs.app-version }}
    - ${{ inputs.base-url }}
    - ${{ inputs.directory }}
